src/Entity/Domain.php
<?php

namespace App\Entity;

use App\Entity\DomainData\DomainDnsRecord;
use App\Entity\Traits\UUIDTrait;
use App\Repository\DomainRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;

#[ORM\Entity(repositoryClass: DomainRepository::class)]
#[ExclusionPolicy("ALL")]
class Domain
{

    use UUIDTrait;

    #[ORM\Column(type: 'string', length: 100, unique: true)]
    #[Expose]
    private $host;

    #[ORM\OneToMany(mappedBy: 'domain', targetEntity: Report::class)]
    private $reports;

    #[ORM\ManyToOne(targetEntity: Analysis::class, inversedBy: 'domains')]
    #[Expose]
    private $analysis;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $soaNameRecord = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $lastCheckAt = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $hostIpAddress = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $whoisData = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $whoisCreationDate = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $whoisExpirationDate = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $whoisUpdateDate = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $whoisOwner = null;

    #[ORM\Column(options: ['default' => 0])]
    private int $reportCount = 0;

    #[ORM\OneToMany(mappedBy: 'domain', targetEntity: DomainDnsRecord::class)]
    private Collection $domainDnsRecords;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'subdomains')]
    private ?self $parentDomain = null;

    #[ORM\OneToMany(mappedBy: 'parentDomain', targetEntity: self::class)]
    private Collection $subdomains;

    public function __construct($host)
    {
        $this->setHost($host);
        $this->reports = new ArrayCollection();
        $this->domainDnsRecords = new ArrayCollection();
        $this->subdomains = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getHost();
    }

    public function getHost(): ?string
    {
        return $this->host;
    }

    public function setHost(string $host): self
    {
        $this->host = $host;

        return $this;
    }

    /**
     * @return Collection<int, Report>
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Report $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports[] = $report;
            $report->setDomain($this);
        }

        return $this;
    }

    public function removeReport(Report $report): self
    {
        if ($this->reports->removeElement($report)) {
            // set the owning side to null (unless already changed)
            if ($report->getDomain() === $this) {
                $report->setDomain(null);
            }
        }

        return $this;
    }

    public function getSelfAnalysis(): ?Analysis {
        return $this->analysis;
    }

    public function getAnalysis(): ?Analysis
    {
        if($analysis = $this->getSelfAnalysis())
            return $analysis;

        if($parent = $this->getParentDomain())
            return $parent->getAnalysis();

        return null;
    }

    public function setAnalysis(?Analysis $analysis): self
    {
        $this->analysis = $analysis;

        return $this;
    }

    public function getSoaNameRecord(): ?string
    {
        return $this->soaNameRecord;
    }

    public function setSoaNameRecord(?string $soaNameRecord): static
    {
        $this->soaNameRecord = $soaNameRecord;

        return $this;
    }

    public function getLastCheckAt(): ?\DateTimeImmutable
    {
        return $this->lastCheckAt;
    }

    public function setLastCheckAt(?\DateTimeImmutable $lastCheckAt): static
    {
        $this->lastCheckAt = $lastCheckAt;

        return $this;
    }

    public function getHostIpAddress(): ?string
    {
        return $this->hostIpAddress;
    }

    public function setHostIpAddress(?string $hostIpAddress): static
    {
        $this->hostIpAddress = $hostIpAddress;

        return $this;
    }

    public function getWhoisData(): ?string
    {
        return $this->whoisData;
    }

    public function setWhoisData(?string $whoisData): static
    {
        $this->whoisData = $whoisData;

        return $this;
    }

    public function getWhoisCreationDate(): ?\DateTimeImmutable
    {
        return $this->whoisCreationDate;
    }

    public function setWhoisCreationDate(?\DateTimeImmutable $whoisCreationDate): static
    {
        $this->whoisCreationDate = $whoisCreationDate;

        return $this;
    }

    public function getWhoisExpirationDate(): ?\DateTimeImmutable
    {
        return $this->whoisExpirationDate;
    }

    public function setWhoisExpirationDate(?\DateTimeImmutable $whoisExpirationDate): static
    {
        $this->whoisExpirationDate = $whoisExpirationDate;

        return $this;
    }

    public function getWhoisUpdateDate(): ?\DateTimeImmutable
    {
        return $this->whoisUpdateDate;
    }

    public function setWhoisUpdateDate(?\DateTimeImmutable $whoisUpdateDate): static
    {
        $this->whoisUpdateDate = $whoisUpdateDate;

        return $this;
    }

    public function getWhoisOwner(): ?string
    {
        return $this->whoisOwner;
    }

    public function setWhoisOwner(?string $whoisOwner): static
    {
        $this->whoisOwner = $whoisOwner;

        return $this;
    }

    public function getReportCount(): ?int
    {
        return $this->reportCount;
    }

    public function increaseReportCount(): static
    {
        $this->reportCount++;

        return $this;
    }

    /**
     * @return Collection<int, DomainDnsRecord>
     */
    public function getDomainDnsRecords(): Collection
    {
        return $this->domainDnsRecords;
    }


    /**
     * @return Collection<int, DnsRecord>
     */
    public function getDnsRecords(): Collection {
        return $this->getDomainDnsRecords()->map(function(DomainDnsRecord $record){
            return $record->getDnsRecord();
        });
    }

    public function addDomainDnsRecord(DomainDnsRecord $domainDnsRecord): static
    {
        if (!$this->domainDnsRecords->contains($domainDnsRecord)) {
            $this->domainDnsRecords->add($domainDnsRecord);
            //$domainDnsRecord->setDomain($this);
        }

        return $this;
    }

    public function removeDomainDnsRecord(DomainDnsRecord $domainDnsRecord): static
    {
        if ($this->domainDnsRecords->removeElement($domainDnsRecord)) {
            // set the owning side to null (unless already changed)
            if ($domainDnsRecord->getDomain() === $this) {
                //$domainDnsRecord->setDomain(null);
            }
        }

        return $this;
    }

    public function getParentDomain(): ?self
    {
        return $this->parentDomain;
    }

    public function setParentDomain(?self $parentDomain): static
    {
        $this->parentDomain = $parentDomain;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getSubdomains(): Collection
    {
        return $this->subdomains;
    }

    public function addSubdomain(self $subdomain): static
    {
        if (!$this->subdomains->contains($subdomain)) {
            $this->subdomains->add($subdomain);
            $subdomain->setParentDomain($this);
        }

        return $this;
    }

    public function removeSubdomain(self $subdomain): static
    {
        if ($this->subdomains->removeElement($subdomain)) {
            // set the owning side to null (unless already changed)
            if ($subdomain->getParentDomain() === $this) {
                $subdomain->setParentDomain(null);
            }
        }

        return $this;
    }

    public function isDangerous(): ?bool
    {
        return $this->getAnalysis()?->getRating()?->isDangerous();
    }

    public function isSafe(): ?bool
    {
        return $this->isDangerous() === false;
    }
}

src/Entity/Rating.php
<?php

namespace App\Entity;

use App\Entity\Traits\UUIDTrait;
use App\Repository\RatingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;

#[ORM\Entity(repositoryClass: RatingRepository::class)]
#[ExclusionPolicy("ALL")]
class Rating
{
    use UUIDTrait;

    #[ORM\Column(type: 'string', length: 30)]
    #[Expose]
    private $title;

    #[ORM\Column(type: 'text', nullable: true)]
    #[Expose]
    private $description;

    #[ORM\Column(type: 'text', nullable: true)]
    private $toDo;

    #[ORM\Column(type: 'string', length: 50)]
    private $cssClass;

    #[ORM\OneToMany(mappedBy: 'rating', targetEntity: Analysis::class)]
    private $analyses;

    #[ORM\Column(type: 'boolean', nullable: true)]
    #[Expose]
    private $isDangerous = null;

    #[ORM\Column(type: 'float', options: ["default" => 0])]
    #[Expose]
    private $level = 0.0;

    public function __construct()
    {
        $this->analyses = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getTitle();
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getToDo(): ?string
    {
        return $this->toDo;
    }

    public function setToDo(?string $toDo): self
    {
        $this->toDo = $toDo;

        return $this;
    }

    public function getCssClass(): ?string
    {
        return $this->cssClass;
    }

    public function setCssClass(string $cssClass): self
    {
        $this->cssClass = $cssClass;

        return $this;
    }

    private function getColor($light): string
    {
        $red = 0;
        $green = 120;
        $angle = ($green - $red) * $this->getLevel() + $red;

        return "hsl({$angle}deg 100% {$light}%)";
    }


    public function getBadgeColor(): string
    {
        return $this->getColor(35);
    }

    public function getBackgroundColor(): string
    {
        return $this->getColor(20);
    }

    /**
     * @return Collection<int, Analysis>
     */
    public function getAnalyses(): Collection
    {
        return $this->analyses;
    }

    public function addAnalysis(Analysis $analysis): self
    {
        if (!$this->analyses->contains($analysis)) {
            $this->analyses[] = $analysis;
            $analysis->setRating($this);
        }

        return $this;
    }

    public function removeAnalysis(Analysis $analysis): self
    {
        if ($this->analyses->removeElement($analysis)) {
            // set the owning side to null (unless already changed)
            if ($analysis->getRating() === $this) {
                $analysis->setRating(null);
            }
        }

        return $this;
    }

    public function isDangerous(): ?bool
    {
        return $this->isDangerous;
    }

    public function setIsDangerous(?bool $isDangerous): self
    {
        $this->isDangerous = $isDangerous;

        return $this;
    }

    public function getLevel(): ?float
    {
        return $this->level;
    }

    public function setLevel(float $level): self
    {
        $this->level = $level;

        return $this;
    }
}

src/Controller/DomainController.php
<?php

namespace App\Controller;

use App\Entity\Domain;
use App\Form\NewCheckType;
use App\Repository\AnalysisRepository;
use App\Repository\DomainRepository;
use App\Repository\ReportRepository;
use App\Service\DomainService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/', name: 'app_domain_')]
class DomainController extends AbstractController
{
    #[Route('/', name: 'search')]
    public function search(Request $request, DomainService $checkService,
                           DomainRepository $domainRepository, ReportRepository $reportRepository,
                           EntityManagerInterface $em): Response
    {

        $newCheckForm = $this->createForm(NewCheckType::class);
        $newCheckForm->handleRequest($request);
        if ($newCheckForm->isSubmitted() && $newCheckForm->isValid()) {

            $element = $newCheckForm->get('element');
            $report = $checkService->getReport($element->getData());
            if (!$report->getDomain()) {
                $element->addError(new FormError("Invalid format"));
            }else{
                $request->getSession()->set(ComplaintController::SESSION_REPORT_VALUE, $report->getValue());
                $em->flush();
                return $this->redirectToRoute('app_domain_check', ['host' => $report->getDomain()->getHost()]);
            }
        }

        return $this->renderForm('domain/search.html.twig', [
            'newCheckForm' => $newCheckForm,
            'reportCount' => $reportRepository->getTotalCount(),
            'notLegitReportCount' => $reportRepository->getNotLegitCount(),
            'recentDangerousDomains' => $domainRepository->findRecentDangerous(),
            'recentDomains' => $domainRepository->findRecent()
        ]);
    }


    #[Route('check/{host}', name: 'check')]
    public function check(Domain $domain, ReportRepository $reportRepository): Response
    {
        return $this->renderForm('domain/show.html.twig', [
            'domain' => $domain,
            'reports' => $reportRepository->findByDomain($domain),
        ]);
    }


    #[Route('recommend', name: 'recommend')]
    public function recommend(AnalysisRepository $analysisRepository): Response
    {
        $analyses = $analysisRepository->findSafe();
        return $this->renderForm('domain/recommend.html.twig', [
            'analyses' => $analyses,
        ]);
    }


    #[Route('blocklist.txt', name: 'blocklist')]
    #[Route('adblocker.txt', name: 'adblock')]
    public function blocklist(DomainRepository $domainRepository, Request $request): Response
    {
        $useAds = str_contains($request->attributes->get('_route'), 'adblock');

        $response = $this->render('domain/blocklist.txt.twig', [
            'useAds' => $useAds,
            'domains' => $domainRepository->findDangerous(),
        ]);

        $response->headers->set('Content-Type', 'text/plain');

        return $response;
    }
}

templates/domain/_list.html.twig
<table>
    {% for domain in domains %}
        <tr>
            <td><a href="{{ path('app_domain_check', {host: domain.host}) }}">{{ domain }}</a></td>

            {% if domain.analysis %}
                <td>{{ domain.analysis.rating }}</td>
                <td class="right">
                    <span class="badge alert {{ domain.analysis.rating.cssClass }}"
                          style="background: {{ domain.analysis.rating.badgeColor }}"></span>
                </td>
            {% else %}
                <td colspan="2">No analysis</td>
            {% endif %}
        </tr>
    {% endfor %}
</table>

templates/domain/blocklist.txt.twig
{% for domain in domains %}
{{ useAds ? ('||'~domain~'^$all') : domain }}
{% endfor  %}

templates/domain/recommend.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reputable sources{% endblock %}
{% block description %}Explore this collection of reputable websites, carefully curated to provide job seekers with access to legitimate opportunities and trustworthy recruiters.{% endblock %}

{% block body %}

    <h1>{{ block('title') }}</h1>

    <p class="intro">
        {{ block('description') }}
    </p>
    <p>
        Each website on this list has undergone a thorough vetting process to ensure high standards of integrity, verified job listings, and a commitment to the best interests of both job seekers and employers.
        With this curated selection, you can confidently navigate your job search journey and avoid scams and unethical practices.
    </p>

    {% for analysis in analyses %}

        <h2>{{ analysis }}</h2>

        {{ include('domain/_list.html.twig', {domains: analysis.domains}) }}

    {% endfor  %}

{% endblock %}

templates/domain/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Check an email address{% endblock %}
{% block description %}{{ block('description_text')|striptags }}{% endblock %}


{% block body %}

    <div id="intro" class="card">

        <h1>Is your source legit?</h1>

        <p class="important">
            {% block description_text -%}
                Are you seeking to <b>confirm the credibility</b> of a job offer, potential collaboration, or other professional correspondence? Employ our verification tool to <b>authenticate an email address or URL</b>.
            {%- endblock %}
        </p>

        {{ form_start(newCheckForm) }}
        {{ form_widget(newCheckForm) }}
        <button type="submit" class="btn">Check &rarr;</button>
        {{ form_end(newCheckForm) }}
    </div>

    {% if recentDangerousDomains %}
        <h2>Recently detected fraud attempts</h2>

        {{ include('domain/_list.html.twig', {domains: recentDangerousDomains}) }}
    {% endif %}

    {% if reportCount %}
        <h2>
            {{ (notLegitReportCount/reportCount*100)|round }}%
            of the {{ reportCount }} checks were not legit
        </h2>

        {{ include('domain/_list.html.twig', {domains: recentDomains}) }}
    {% endif %}

{% endblock %}

templates/domain/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Is {{ domain }} a legit website?{% endblock %}
{% block description %}Verify the legitimacy of the domain {{ domain }} with our reliable verification tool. Our page provides a comprehensive analysis and evaluation of {{ domain }}, ensuring you can distinguish between authentic and potentially fraudulent online entities. Stay protected and make informed decisions while interacting with the {{ domain }} domain using our trusted verification service.{% endblock %}

{% block body %}

    <h1>{{ block('title') }}</h1>

    <p>
        Did you receive an email from someone with an address <i>@{{ domain }}</i>?
        Did you find some information or an offer on a website starting by <i>http(s)://{{ domain }}</i>?
    </p>

    {% if domain.isSafe %}
        <p>
            Is it legit? Short answer: <b>yes</b>.
            However, if there are other URLs or email addresses in the content you are trying to verify for legitimacy, you should also check them.
        </p>
    {% endif %}

    {% set analysis = domain.analysis ?? false %}
    {% if analysis %}

        {% set rating = analysis.rating %}

        <div class="card alert {{ rating.cssClass }}" style="background: {{ rating.backgroundColor }}">


            <h2>{{ rating.title }}: {{ analysis.title }}</h2>

            {% if rating.description or analysis.instructions %}
                <h3>What does that mean?</h3>
                {% if rating.description %}
                    <p>
                        {{ rating.description }}
                    </p>
                {% endif %}
                {% if analysis.instructions %}
                    <p>
                        {{ analysis.instructions }}
                    </p>
                {% endif %}
            {% endif %}

            {% if domain.isSafe %}
                <h3>Visit this website</h3>
                <p>
                    <a href="https://{{ domain.host }}" class="btn secondary" target="_blank" rel="noopener follow referrer">Go to {{ domain }}</a>
                </p>
            {% endif %}

            {% if domain.isDangerous %}
                <h3>Were you targeted by {{ domain }}?</h3>
                <p>
                    If you suspect or have encountered a scam or fraudulent activity involving {{ domain }},
                    please report it immediately:
                </p>
                <p>
                    <a href="{{ path('complaint_create') }}" class="btn secondary block lg">Complain about {{ domain }}</a>
                </p>
            {% endif %}

        </div>

        {% if domain.parentDomain %}
            {% set parent = domain.parentDomain %}
            <h3>Part of {{ parent }}</h3>
            <p>
                The domain {{ domain }} has been marked as being part of {{ parent }}:
                <a href="{{ path('app_domain_check', {host: parent.host}) }}">see {{ parent }} analysis</a>.
            </p>
        {% endif %}

        {% if rating.todo ?? false %}
            <h3>What should you do?</h3>
            <p>
                {{ rating.todo }}
            </p>
        {% endif %}

        {% if reports|length > 5 %}
            <h3>How many times has {{ domain }} been checked?</h3>

            <p>
                This domain has been checked <b>{{ reports|length }} times</b>.
                {% if domain.analysis.rating.isDangerous %}
                    This number can potentially correspond to the number of uncovered fraud schemes committed via {{ domain }}.
                {% endif %}
            </p>

        {% endif %}

    {% else %}
        <div class="card">
            <h2>Under review</h2>
            <p>
                This domain is currently reviewed by our team. We do not recommend to use it for the moment.
            </p>
        </div>
    {% endif %}

{% endblock %}