src/Entity/Complaint/Complaint.php
<?php

namespace App\Entity\Complaint;

use App\Entity\Traits\UUIDTrait;
use App\Repository\Complaint\ComplaintRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Country;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\PositiveOrZero;

#[ORM\Entity(repositoryClass: ComplaintRepository::class)]
#[ORM\Table(name: 'complaint')]
class Complaint
{
    use UUIDTrait;

    #[ORM\Column(length: 200)]
    #[Email]
    private ?string $email = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    #[PositiveOrZero]
    private ?float $moneySent = null;

    #[ORM\Column(length: 100)]
    #[Country]
    private ?string $country = null;

    #[ORM\Column(length: 200)]
    private ?string $code = null;

    #[ORM\ManyToOne(inversedBy: 'complaints')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ComplaintStatus $status = null;

    #[ORM\OneToMany(mappedBy: 'complaint', targetEntity: ComplaintReport::class)]
    private Collection $complaintReports;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTimeImmutable('now'));
        $this->resetCode();
        $this->complaintReports = new ArrayCollection();
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getMoneySent(): ?float
    {
        return $this->moneySent;
    }

    public function setMoneySent(?float $moneySent): static
    {
        $this->moneySent = $moneySent;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function resetCode(): static
    {

        $this->code = bin2hex(random_bytes(16));

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    private function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getStatus(): ?ComplaintStatus
    {
        return $this->status;
    }

    public function setStatus(?ComplaintStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, ComplaintReport>
     */
    public function getComplaintReports(): Collection
    {
        return $this->complaintReports;
    }

    public function addComplaintReport(ComplaintReport $complaintReport): static
    {
        if (!$this->complaintReports->contains($complaintReport)) {
            $this->complaintReports->add($complaintReport);
            $complaintReport->setComplaint($this);
        }

        return $this;
    }

    public function removeComplaintReport(ComplaintReport $complaintReport): static
    {
        if ($this->complaintReports->removeElement($complaintReport)) {
            // set the owning side to null (unless already changed)
            if ($complaintReport->getComplaint() === $this) {
                $complaintReport->setComplaint(null);
            }
        }

        return $this;
    }

    public function getReports(): Collection
    {
        return $this->complaintReports->map(fn($complaintReport) => $complaintReport->getReport());
    }
}

src/Entity/DomainData/DnsRecord.php
<?php

namespace App\Entity\DomainData;

use App\Entity\Analysis;
use App\Entity\Domain;
use App\Entity\Traits\UUIDTrait;
use App\Repository\DomainData\DnsRecordRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: DnsRecordRepository::class)]
#[ORM\Table(name: 'domain_data__dns_records')]
#[ORM\UniqueConstraint(
    name: 'unique_record',
    columns: ['record_type', 'value']
)]
class DnsRecord
{
    use UUIDTrait;

    #[ORM\Column(length: 20)]
    private ?string $recordType = null;

    #[ORM\Column(length: 255)]
    private ?string $value = null;

    #[ORM\OneToMany(mappedBy: 'dnsRecord', targetEntity: DomainDnsRecord::class)]
    private Collection $domainDnsRecords;

    #[ORM\ManyToOne(inversedBy: 'associatedDnsRecords')]
    private ?Analysis $applyAnalysis = null;

    public function __construct(string $recordType, string $value)
    {
        $this->setRecordType($recordType);
        $this->setValue($value);
        $this->domainDnsRecords = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getRecordType() . ' ' . $this->getValue();
    }

    public function getRecordType(): ?string
    {
        return $this->recordType;
    }

    private function setRecordType(string $recordType): static
    {
        $this->recordType = $recordType;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    private function setValue(string $value): static
    {
        $this->value = $value;

        return $this;
    }

    /**
     * @return Collection<int, DomainDnsRecord>
     */
    public function getDomainDnsRecords(): Collection
    {
        return $this->domainDnsRecords;
    }

    public function addDomainDnsRecord(DomainDnsRecord $domainDnsRecord): static
    {
        if (!$this->domainDnsRecords->contains($domainDnsRecord)) {
            $this->domainDnsRecords->add($domainDnsRecord);
            //$domainDnsRecord->setDnsRecord($this);
        }

        return $this;
    }

    public function removeDomainDnsRecord(DomainDnsRecord $domainDnsRecord): static
    {
        if ($this->domainDnsRecords->removeElement($domainDnsRecord)) {
            // set the owning side to null (unless already changed)
            if ($domainDnsRecord->getDnsRecord() === $this) {
                //$domainDnsRecord->setDnsRecord(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Domain>
     */
    public function getDomains(): Collection {
        return $this->getDomainDnsRecords()->map(fn(DomainDnsRecord $domainDnsRecord) => $domainDnsRecord->getDomain());
    }

    /**
     * @return Collection<int, Domain>
     */
    public function getDangerousDomains(): Collection {
        return $this->getDomains()->filter(fn(Domain $domain) => $domain->getAnalysis()?->getRating()?->isDangerous() ?? false);
    }

    public function getApplyAnalysis(): ?Analysis
    {
        return $this->applyAnalysis;
    }

    public function setApplyAnalysis(?Analysis $applyAnalysis): static
    {
        $this->applyAnalysis = $applyAnalysis;

        return $this;
    }
}

src/Controller/InvestigationController.php
<?php

namespace App\Controller;

use App\Entity\Domain;
use App\Form\EditDnsRecordAnalysisType;
use App\Form\EditDomainType;
use App\Repository\DomainData\DnsRecordRepository;
use App\Entity\DomainData\DnsRecord;
use App\Repository\DomainRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin', name: 'investigation_')]
#[IsGranted('ROLE_ADMIN')]
class InvestigationController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(): Response
    {
        return $this->redirectToRoute('investigation_domain_index');
    }
    #[Route('/dns', name: 'dns_index')]
    public function dns_index(DnsRecordRepository $recordRepository): Response
    {
        $dnsRecords = $recordRepository->findSorted();
        return $this->render('admin/investigation/dns_index.html.twig', [
            'dnsRecords' => $dnsRecords,
        ]);
    }

    #[Route('/dns/record/{id}', name: 'dns_show')]
    public function dns_show(DnsRecord $record, Request $request, EntityManagerInterface $em): Response
    {
        $editForm = $this->createForm(EditDnsRecordAnalysisType::class, $record);
        $editForm->handleRequest($request);
        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $em->flush();
            return $this->redirectToRoute('investigation_dns_show', ['id' => $record->getId()]);
        }

        return $this->render('admin/investigation/dns_show.html.twig', [
            'record' => $record,
            'editForm' => $editForm->createView(),
        ]);
    }

    #[Route('/domain', name: 'domain_index')]
    public function domain_index(DomainRepository $domainRepository): Response {
        $domains = $domainRepository->findToAnalyse();
        return $this->render('admin/investigation/domain_index.html.twig', [
            'domains' => $domains,
        ]);
    }

    #[Route('/domain/edit/{host}', name: 'domain_edit')]
    public function domain_edit(Domain $domain, Request $request, EntityManagerInterface $em): Response
    {
        $editForm = $this->createForm(EditDomainType::class, $domain);
        $editForm->handleRequest($request);
        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $em->flush();
            return $this->redirectToRoute('investigation_domain_index');
        }

        return $this->renderForm('admin/investigation/domain_edit.html.twig', [
            'editForm' => $editForm,
            'domain' => $domain,
        ]);
    }
}

templates/investigation/dns_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Investigation tools{% endblock %}

{% block body %}

    <h1>Investigation tools</h1>

    <h2>DNS Records</h2>

    <table>
    {% for record in dnsRecords %}
        <tr>
            <td>
                {{ record.recordType }}
            </td>
            <td>
                {{ record.domains|length }}
            </td>
            <td>
                {% if record.applyAnalysis %}
                    <small>
                        {{ record.applyAnalysis }}
                    </small>
                {% elseif record.dangerousDomains|length %}
                    {{ (record.dangerousDomains|length / record.domains|length * 100)|round(2) }}%
                {% endif %}
            </td>
            <td>
                <a href="{{ path('investigation_dns_show', {id: record.id}) }}">{{ record.value }}</a>
            </td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}

templates/investigation/dns_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ record }}{% endblock %}

{% block body %}

    <h1>{{ block('title') }}</h1>

    <h2>Domains</h2>

    {{ include('domain/_list.html.twig', {domains: record.domains}) }}

    <h2>Records</h2>

    {{ form_start(editForm) }}
    {{ form_widget(editForm) }}
    <button type="submit" class="btn">Save</button>
    {{ form_end(editForm) }}

{% endblock %}

templates/investigation/domain_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin {{ domain }}{% endblock %}

{% block body %}

    <h1>{{ block('title') }}</h1>

    {{ include('_components/form.html.twig', {form: editForm}) }}

    <h2>DNS records</h2>

    <table>
        {% for record in domain.dnsRecords %}
            <tr>
                <td>{{ record.recordType }}</td>
                <td><a href="{{ path('investigation_dns_show', {id: record.id}) }}">{{ record.value }}</a></td>
            </tr>
        {% endfor %}
    </table>

    <h2>Reports</h2>

    <table>
        {% for report in domain.reports %}
            <tr>
                <td>{{ report.value }}</td>
                <td>{{ report.createdAt|date('Y-m-d H:i:s') }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/investigation/domain_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin domains{% endblock %}

{% block body %}

    <h1>{{ block('title') }}</h1>

    <h2>Domains</h2>

    <table>
        {% for domain in domains %}
            <tr>
                <td>{{ domain }}</td>
                <td>{{ domain.reportCount }}&times;</td>
                <td><a href="{{ path('investigation_domain_edit', {host: domain.host}) }}">Edit</a></td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/investigation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Investigation tools{% endblock %}

{% block body %}

    <h1>Investigation tools</h1>

    <h2>DNS Records</h2>

    <table>
    {% for record in dnsRecords %}
        <tr>
            <td>
                {{ record.recordType }}
            </td>
            <td>
                {{ record.domains|length }}
            </td>
            <td>
                {% if record.applyAnalysis %}
                    <small>
                        {{ record.applyAnalysis }}
                    </small>
                {% elseif record.dangerousDomains|length %}
                    {{ (record.dangerousDomains|length / record.domains|length * 100)|round(2) }}%
                {% endif %}
            </td>
            <td>
                <a href="{{ path('investigation_dns_show', {id: record.id}) }}">{{ record.value }}</a>
            </td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}